language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

cache:
  directories:
    - ./vendor

install:
  - composer --prefer-source install

script:
  - vendor/bin/phpunit
  - bin/psalm
  - vendor/bin/phpcs
